# Generated by Django 4.2.4 on 2023-08-17 12:55

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_sight', models.CharField(max_length=30, unique=True, verbose_name='Name of Sight')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('description', models.TextField(verbose_name='Description')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('pros', models.TextField(blank=True, null=True, verbose_name='Pros')),
                ('cons', models.TextField(blank=True, null=True, verbose_name='Cons')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SightLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web.sight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SightComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('publication_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('sight', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sight_comments', to='web.sight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
